Set better defaults for example templates
sulu/sulu-minimal pull request #100
Opened 2018-05-30 17:49 UTC by alexander-schranz

The current cacheLifeTime set in the xmls are not recommended values to be used in real world environment.

2018-05-30 17:50 UTC, alexander-schranz commented on app/Resources/templates/pages/default.xml
> +    <cacheLifetime>1209600</cacheLifetime>
2 weeks

2018-05-30 17:50 UTC, alexander-schranz commented on app/Resources/templates/pages/homepage.xml
> +    <cacheLifetime>86400</cacheLifetime>
1 day

2018-05-31 10:08 UTC, chirimoya requested changes

2018-05-31 10:08 UTC, chirimoya commented on app/Resources/templates/pages/default.xml
> +    <cacheLifetime>1209600</cacheLifetime>
1 week

2018-05-31 13:25 UTC, alexander-schranz commented
@chirimoya updated

2018-05-31 14:55 UTC, chirimoya approved these changes

2018-05-31 14:56 UTC, merged