Fix creation of .env file composer create project
sulu/sulu-minimal pull request #119
Opened 2018-10-15 13:11 UTC by alexander-schranz

2018-10-15 15:25 UTC, danrot commented
This is the fix for #118. And I would not move the NPM tests to circle ci, since seem to have install the composer dependencies there as well...

2018-10-15 17:49 UTC, alexander-schranz commented
@danrot travis is splitted in 2 test cases one using env variables and one uses the .env file with composer create-project.

2018-10-16 05:42 UTC, danrot requested changes

2018-10-16 05:42 UTC, danrot commented on .travis.yml
> +  - pwd
Are this two commands remaining from testing?

2018-10-16 05:44 UTC, danrot requested changes

2018-10-16 05:44 UTC, danrot commented on .travis.yml
> +  - echo $TRAVIS_PULL_REQUEST_SLUG
These are probably also remainders from testing, right?

2018-10-16 07:36 UTC, danrot approved these changes

2018-10-16 07:36 UTC, merged