Use HttpCache only in website kernel
sulu/sulu-minimal pull request #150
Opened 2019-01-08 08:41 UTC by trickreich

| Q | A
| --- | ---
| Bug fix? | no
| New feature? | yes
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes --
| Related issues/PRs | --
| License | MIT
| Documentation PR | --

#### What's in this PR?

Use HttpCache only in website kernel.

#### Why?

In the admin kernel it's not necessary.

2019-01-08 14:37 UTC, alexander-schranz commented
@trickreich somebody at the SymfonyCon also said that the HttpCacheKernel is better to lazy initialize:

```diff
diff --git a/src/Kernel.php b/src/Kernel.php
index c543e8e..5ade468 100644
--- a/src/Kernel.php
+++ b/src/Kernel.php
@@ -17,16 +17,19 @@ use Sulu\Bundle\HttpCacheBundle\Cache\SuluHttpCache;
 use Sulu\Component\HttpKernel\SuluKernel;
 use Symfony\Component\Config\Loader\LoaderInterface;
 use Symfony\Component\DependencyInjection\ContainerBuilder;
+use Symfony\Component\HttpKernel\HttpCache\HttpCache;
+use Symfony\Component\HttpKernel\HttpKernelInterface;
 
 class Kernel extends SuluKernel implements HttpCacheProvider
 {
-    use HttpCacheAware;
+    /**
+     * @var HttpKernelInterface
+     */
+    private $httpCache;
 
     public function __construct(string $environment, bool $debug, string $suluContext)
     {
         parent::__construct($environment, $debug, $suluContext);
-        // HttpCache and HttpCacheProvider is not needed when using varnish
-        $this->setHttpCache(new SuluHttpCache($this));
     }
 
     protected function configureContainer(ContainerBuilder $container, LoaderInterface $loader)
@@ -38,4 +41,13 @@ class Kernel extends SuluKernel implements HttpCacheProvider
 
         parent::configureContainer($container, $loader);
     }
+
+    public function getHttpCache()
+    {
+        if (!$this->httpCache) {
+            $this->httpCache = new SuluHttpCache($this);
+        }
+
+        return $this->httpCache;
+    }
 }
```

2019-01-14 18:46 UTC, alexander-schranz approved these changes

2019-01-15 21:11 UTC, alexander-schranz commented
@trickreich styleci seems not be active. unused `use` statements.

2019-01-23 07:51 UTC, danrot requested changes

2019-01-23 07:51 UTC, danrot commented on src/Kernel.php
> -    use HttpCacheAware;
Should also be removed from `use` statements, right? And just curious: Why did we change that?

2019-01-23 07:52 UTC, danrot commented on src/Kernel.php
> -    use HttpCacheAware;
Ah, have seen the comment from @alexander-schranz...

2019-01-31 14:36 UTC, merged