Added config to enable doctrine entities
sulu/sulu-minimal pull request #21
Opened 2016-09-07 08:41 UTC by wachterjohannes

This PR enables the indexing of doctrine entities.

2016-10-06 11:12 UTC, danrot commented
Should that be a hotfix or not? It's named hotfix, but the target branch is develop.

2016-10-06 12:26 UTC, wachterjohannes commented
it could also be included in 1.3 release but it s not that important

2016-11-07 13:32 UTC, danrot requested changes

2016-11-07 13:32 UTC, danrot commented on app/config/config.yml
> +            enabled: true
Shouldn't that be the default value? Then we wouldn't have to add it to the configuration...

2016-11-07 14:33 UTC, wachterjohannes commented on app/config/config.yml
> +            enabled: true
currently the default-value is false.

2016-11-08 08:14 UTC, danrot commented
@wachterjohannes Could you please rebase? Then I would test and merge it.

2016-11-08 08:37 UTC, wachterjohannes commented
@danrot is rebased.

2016-11-08 08:53 UTC, danrot commented on app/config/config.yml
> +            enabled: true
Actually it looks like you made the default value to true 😉 
https://github.com/sulu/sulu/blame/b81a56e6357924d1ba8fd060bacdf5571ef6a8d6/src/Sulu/Bundle/SearchBundle/DependencyInjection/SuluSearchExtension.php#L48

2016-11-08 10:38 UTC, danrot approved these changes

2016-11-08 10:39 UTC, merged