Added automation-bundle
sulu/sulu-minimal pull request #31
Opened 2016-11-29 11:33 UTC by wachterjohannes

Main PR https://github.com/sulu/sulu/pull/3037

2016-11-29 12:47 UTC, danrot requested changes

2016-11-29 12:47 UTC, danrot commented on composer.json
> +        "php-task/php-admitask": "@dev"
That's an error, right?

2016-11-29 13:30 UTC, wachterjohannes commented on composer.json
> +        "php-task/php-admitask": "@dev"
yes thats an error (:

2016-11-29 15:09 UTC, wachterjohannes commented
@danrot fixed

2016-12-05 09:15 UTC, danrot commented
Please update all the dependencies to a stable one, and create a corresponding PR for sulu-standard.

2016-12-05 09:37 UTC, wachterjohannes commented
@danrot updated sulu dependency to develop

2016-12-05 10:47 UTC, danrot approved these changes

2016-12-05 10:47 UTC, merged