Test builder with travis
sulu/sulu-minimal pull request #79
Opened 2017-12-07 15:33 UTC by alexander-schranz

2017-12-07 15:57 UTC, alexander-schranz commented on .travis.yml
> +        - COMPOSER_FLAGS="--prefer-dist --no-interaction"
this is not set to lowest as we want to test the actual sulu version and not 1.6.0

2017-12-13 19:36 UTC, danrot requested changes

2017-12-13 19:36 UTC, danrot commented on .travis.yml
> +  # Test if PHPUnit isntallation works
`installation`

2017-12-13 19:36 UTC, danrot commented on .travis.yml
> +
Looks like a new line too much

2017-12-13 19:36 UTC, danrot commented on .travis.yml
> +    - php: 5.5
5.5 doesn't seem to work anymore :-)

2017-12-21 09:31 UTC, danrot approved these changes

2017-12-21 09:49 UTC, merged